apiVersion: v2
name: coroot
description: A monitoring and troubleshooting tool for microservice architectures.
type: application
version: 0.2.44
appVersion: "0.17.11"
dependencies:
  - name: prometheus
    repository: http://localhost:8088
    version: 23.1.*
    condition: prometheus.enabled
  - name: node-agent
    version: 0.1.34
    repository: https://coroot.github.io/helm-charts
    condition: node-agent.enabled
  - name: pyroscope
    repository: https://pyroscope-io.github.io/helm-chart
    version: 0.2.*
    condition: pyroscope.enabled
  - name: pyroscope-ebpf
    repository: https://pyroscope-io.github.io/helm-chart
    version: 0.1.*
    condition: pyroscope-ebpf.enabled
  - name: clickhouse
    version: 3.5.*
    repository: http://localhost:8088
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.52.*
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
