apiVersion: v2
name: coroot
description: A monitoring and troubleshooting tool for microservice architectures.
type: application
version: 0.7.0
appVersion: "0.25.0"
dependencies:
  - name: prometheus
    repository: http://localhost:8088
    version: 25.8.0
    condition: prometheus.enabled
  - name: node-agent
    version: 0.1.51
    repository: http://localhost:8088
    condition: node-agent.enabled
  - name: pyroscope
    repository: http://localhost:8088
    version: 0.2.92
    condition: pyroscope.enabled
  - name: clickhouse
    version: 4.1.8
    repository: http://localhost:8088
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.52.1
    repository: http://localhost:8088
    condition: opentelemetry-collector.enabled
